#!/usr/bin/env python3

import sys
import fputs

if __name__ == "__main__":
    """
    try:
        output = fputs.fputs('Test\n', 'write.txt')
    #except ValueError:
    except fputs.ShortStringError:
        print('exception worked')
    print()
    print(fputs.CONST_1)
    print(fputs.CONST_2)
    print(fputs.MACRO_1)
    print(fputs.MACRO_2)
    print()
    output = fputs.fputs('TestTest\n', 'write.txt')    
    print(type(output))
    print(output)
    print()
    output = fputs.system('ls -rtlha')
    print(output)
    print()
    output = fputs.dv_example(666, 'Alpha')
    print()
    """
    v = fputs.build_values();
    print(type(v))
    print(v)
    sys.exit(0)

